#############################################################################
# Makefile for building: airmap.app/Contents/MacOS/airmap
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  ../airmap/airmap.pro
# Template: app
# Command: /Applications/Qt5.4.0/5.4/ios/bin/qmake -spec macx-ios-clang CONFIG+=x86 CONFIG+=iphonesimulator -spec macx-xcode -o airmap.xcodeproj/project.pbxproj ../airmap/airmap.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Applications/Qt5.4.0/5.4/ios/bin/qmake
airmap.xcodeproj/project.pbxproj: ../airmap/airmap.pro /Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/qmake.conf /Applications/Qt5.4.0/5.4/ios/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/qdevice.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/device_config.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/shell-unix.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/unix.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/mac.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/ios.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/clang.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/ios/clang.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/common/ios/qmake.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/qconfig.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qdds.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qjp2.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmng.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/qt_config.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt_config.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-xcode/qmake.conf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/default_pre.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_pre.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/default_post.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/c++11.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/warn_on.prf \
		/Applications/Qt5.4.0/5.4/ios/plugins/platforms/libqios_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/qt.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/resources.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/moc.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/uic.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/exceptions.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/yacc.prf \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/features/lex.prf \
		../airmap/airmap.pro \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		/Applications/Qt5.4.0/5.4/ios/lib/libQt5PlatformSupport_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/lib/libQt5Gui_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/lib/libQt5Core_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/lib/libqtharfbuzzng_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/lib/libQt5Widgets_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqdds_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqicns_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqico_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqjp2_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqmng_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqtga_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqtiff_iphonesimulator_debug.prl \
		/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqwbmp_iphonesimulator_debug.prl
	$(QMAKE) -spec macx-ios-clang CONFIG+=x86 CONFIG+=iphonesimulator -spec macx-xcode -o airmap.xcodeproj/project.pbxproj ../airmap/airmap.pro
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/spec_pre.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/qdevice.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/device_config.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/shell-unix.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/unix.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/mac.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/ios.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/clang.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/clang-mac.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/ios/clang.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/common/ios/qmake.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/qconfig.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qdds.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qico.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qios.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qjp2.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmng.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/qt_functions.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/qt_config.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt_config.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/qmake.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-xcode/qmake.conf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/exclusive_builds.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/default_pre.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_pre.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_pre.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/resolve_config.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/default_post.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/sdk.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_post.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/c++11.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/objective_c.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/warn_on.prf:
/Applications/Qt5.4.0/5.4/ios/plugins/platforms/libqios_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/qt.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/resources.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/moc.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/unix/opengl.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/uic.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/unix/thread.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/mac/rez.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/testcase_targets.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/exceptions.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/yacc.prf:
/Applications/Qt5.4.0/5.4/ios/mkspecs/features/lex.prf:
../airmap/airmap.pro:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Applications/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
/Applications/Qt5.4.0/5.4/ios/lib/libQt5PlatformSupport_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/lib/libQt5Gui_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/lib/libQt5Core_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/lib/libqtharfbuzzng_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/lib/libQt5Widgets_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqdds_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqicns_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqico_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqjp2_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqmng_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqtga_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqtiff_iphonesimulator_debug.prl:
/Applications/Qt5.4.0/5.4/ios/plugins/imageformats/libqwbmp_iphonesimulator_debug.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-ios-clang CONFIG+=x86 CONFIG+=iphonesimulator -spec macx-xcode -o airmap.xcodeproj/project.pbxproj ../airmap/airmap.pro

qmake_all: FORCE

